#pragma once
// Generated by fit_nnue_wdl_calibration.py from the sealed calibration run
// logs/nnue_wdl_calibration_20260729_120718/fit_v2.

#include <algorithm>
#include <array>
#include <cmath>

namespace chess::wdl_calibration {

struct Wdl {
    double loss;
    double draw;
    double win;
};

inline constexpr const char* formula = "symmetric_phase_ply";
inline constexpr const char* calibration_run =
    "nnue_wdl_calibration_20260729_120718/fit_v2";
inline constexpr std::array<double, 5> signed_weights = {
    0.70435256349200226,
    0.19483567929398329,
    1.1337187287758814,
    -0.071978930643792349,
    0.29924977017179077,
};
inline constexpr std::array<double, 10> draw_weights = {
    2.4760634024607553,
    -1.6160465937550406,
    0.46118158639068113,
    -1.5368488644715408,
    -0.046298750448132441,
    1.5634049176069302,
    2.2598281664656752,
    0.061371926584069071,
    -0.16503851158566316,
    -1.0696296185724046,
};

inline Wdl probabilities(int cp, int phase_index, int absolute_ply) {
    const double z = std::clamp(cp / 1000.0, -2.0, 2.0);
    const double abs_z = std::abs(z);
    const double phase = std::clamp(phase_index / 7.0, 0.0, 1.0);
    const double ply = std::clamp(absolute_ply / 240.0, 0.0, 1.0);
    const std::array<double, 5> signed_features = {
        z,
        std::tanh(z / 0.15),
        std::tanh(z / 0.4),
        z * phase,
        z * ply,
    };
    const std::array<double, 10> draw_features = {
        1.0,
        abs_z,
        abs_z * abs_z,
        phase,
        phase * phase,
        ply,
        ply * ply,
        abs_z * phase,
        abs_z * ply,
        phase * ply,
    };
    double signed_logit = 0.0;
    double draw_logit = 0.0;
    for (std::size_t i = 0; i < signed_weights.size(); ++i) {
        signed_logit += signed_weights[i] * signed_features[i];
    }
    for (std::size_t i = 0; i < draw_weights.size(); ++i) {
        draw_logit += draw_weights[i] * draw_features[i];
    }
    const double maximum =
        std::max({-signed_logit, draw_logit, signed_logit});
    const double loss = std::exp(-signed_logit - maximum);
    const double draw = std::exp(draw_logit - maximum);
    const double win = std::exp(signed_logit - maximum);
    const double total = loss + draw + win;
    return {loss / total, draw / total, win / total};
}

inline double expected_score(int cp, int phase_index, int absolute_ply) {
    const Wdl wdl = probabilities(cp, phase_index, absolute_ply);
    return wdl.win + 0.5 * wdl.draw;
}

inline double expected_score_loss(
    int teacher_cp,
    int candidate_cp,
    int phase_index,
    int absolute_ply
) {
    return std::abs(
        expected_score(teacher_cp, phase_index, absolute_ply)
        - expected_score(candidate_cp, phase_index, absolute_ply));
}

}  // namespace chess::wdl_calibration
